// Full-game training log in the OpenAI chat-completions format:
// { "messages": [ {role, content}, ... ] } — system prompt once, then EVERY
// user (board state) and assistant (model reply) turn, unabridged. The live
// LLM context omits history to save tokens; this log does not. Rewritten
// atomically after every exchange so a crash loses nothing.

import * as fs from "node:fs";
import * as path from "node:path";
import type { ChatMessage, TokenUsage } from "./llm.js";

export interface UsageTotals {
  llmCalls: number;
  /** tokens sent to the model (prompts); "in" from the model's perspective */
  tokensIn: number;
  /** tokens generated by the model (completions) */
  tokensOut: number;
}

export class GameLog {
  private messages: ChatMessage[] = [];
  private file: string | null = null;
  private dir: string;
  private totals: UsageTotals = { llmCalls: 0, tokensIn: 0, tokensOut: 0 };

  constructor(dir: string) {
    this.dir = dir;
  }

  /** Start a fresh log; called once the room code is known. */
  begin(roomCode: string, systemPrompt: string): void {
    fs.mkdirSync(this.dir, { recursive: true });
    // pid suffix: two bots spawned in the same millisecond (e.g. via the
    // spawner) must not collide on the same file
    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    this.file = path.join(this.dir, `${roomCode}-${stamp}-${process.pid}.json`);
    this.messages = [{ role: "system", content: systemPrompt }];
    this.totals = { llmCalls: 0, tokensIn: 0, tokensOut: 0 };
    this.flush();
  }

  /** Record one LLM call's token usage (from the OpenRouter response). */
  addUsage(usage: TokenUsage | null): void {
    this.totals.llmCalls++;
    if (usage) {
      this.totals.tokensIn += usage.promptTokens;
      this.totals.tokensOut += usage.completionTokens;
    }
    this.flush();
  }

  get usage(): UsageTotals {
    return { ...this.totals };
  }

  append(role: "user" | "assistant", content: string): void {
    if (!this.file) return; // not started yet
    this.messages.push({ role, content });
    this.flush();
  }

  get path(): string | null {
    return this.file;
  }

  private flush(): void {
    if (!this.file) return;
    const tmp = this.file + ".tmp";
    fs.writeFileSync(tmp, JSON.stringify({ usage: this.totals, messages: this.messages }, null, 2));
    fs.renameSync(tmp, this.file);
  }
}
